### ISSUE TITLE
Using live & sandbox modes simultaniously and getting ApiException{statusCode: 404}

### ISSUE THREAD

**Issue by jimmyff** [Omnimind-Ltd/app-store-server-sdk#1]
Hey,

Firstly thanks for this plugin! I'm running in to an issue when I try to use both the live and sandbox simultaneously to verify payment receipts. I'm doing this as my app was just rejected due to the fact that I was only checking production purchases, here is Apple's feedback:

> ### Next Steps
> 
> When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code "Sandbox receipt used in production," you should validate against the test environment instead.

To implement this I'm doing something this:

```dart
        var order =
            await appstoreLive.lookUpOrderId(receipt.providerTransactionRef);

        // Check sanbox...
        if (order.status != 0) {
          log.info('APPSTORE: invalid live purchase, trying sandbox');
          var sandboxOrder = await appstoreSandbox
              .lookUpOrderId(receipt.providerTransactionRef);
          if (sandboxOrder.status == 0) {
            log.info('APPSTORE: Sandbox order valid');
            order = sandboxOrder;
          }
        }
```

However the sanbox client is failing with a 404 error:

```
ApiException{statusCode: 404, error: null}

#0      AppStoreServerHttpClient._makeRequest (package:app_store_server_sdk/src/io/app_store_server_http_client.dart:176)
<asynchronous suspension>
#1      AppStoreServerAPI.lookUpOrderId (package:app_store_server_sdk/src/app_store_server_api.dart:67)
<asynchronous suspension>
#2      AppleAppStorePaymentProvider._processPurchase (package:cloud_functions_core/src/payments/providers/apple_app_store_provider.dart:47)
<asynchronous suspension>
#3      AppleAppStorePaymentProvider.updateReceipt (package:cloud_functions_core/src/payments/providers/apple_app_store_provider.dart:29)
<asynchronous suspension>
#4      PaymentProcessor.processPurchaseReceipt (package:cloud_functions_core/src/payments/payment_processor.dart:90)
<asynchronous suspension>
#5      corsFunction (package:payment_processor/functions.dart:68)
<asynchronous suspension>
#6      cloudLoggingMiddleware.hostedLoggingMiddleware.<anonymous closure>.<anonymous closure> (package:functions_framework/src/logging.dart:171)
<asynchronous suspension>
```

I'm not sure if it's the JWT token that's causing an issue, I'm maintaining two JWT tokens, one for live and one for sandbox. 

Do you have any idea why I'm getting a 404 for sandbox lookups?

This is running in a Cloud Run instance & my version is:
```
  app_store_server_sdk:
    dependency: transitive
    description:
      name: app_store_server_sdk
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.5"
```

FYI: The github issues URL is broken on the readme.md

**Comment by jimmyff** [comment]
Doing some more testing and `lookUpOrderId()` on sandbox always returns a 404.

Also I'm not convinced that `lookUpOrderId (orderId)` is working on live? It always returns status: 1. Here is the response when I lookup my order: `240001281972903`
```
Order: OrderLookupResponse{status: 1, signedTransactions: null}
```

Yet I POST the receipt data to  the `'https://buy.itunes.apple.com/verifyReceipt'` it returns it as valid and lists `240001281972903` as a valid `transaction_id` in `in_app`.

```json
{
    "receipt": {
        "receipt_type": "Production",
        "adam_id": 6443775589,
        "app_item_id": 6443775589,
        "bundle_id": "com.myapp.app",
        "application_version": "57",
        "download_id": 501864415039396258,
        "version_external_identifier": 853018761,
        "receipt_creation_date": "2022-11-24 18:05:02 Etc/GMT",
        "receipt_creation_date_ms": "1669313102000",
        "receipt_creation_date_pst": "2022-11-24 10:05:02 America/Los_Angeles",
        "request_date": "2022-11-24 18:35:53 Etc/GMT",
        "request_date_ms": "1669314953638",
        "request_date_pst": "2022-11-24 10:35:53 America/Los_Angeles",
        "original_purchase_date": "2022-10-25 17:51:24 Etc/GMT",
        "original_purchase_date_ms": "1666720284000",
        "original_purchase_date_pst": "2022-10-25 10:51:24 America/Los_Angeles",
        "original_application_version": "20",
        "in_app": [
            {
                "quantity": "1",
                "product_id": "like_1",
                "transaction_id": "240001281972903",
                "original_transaction_id": "240001281972903",
                "purchase_date": "2022-11-24 18:05:01 Etc/GMT",
                "purchase_date_ms": "1669313101000",
                "purchase_date_pst": "2022-11-24 10:05:01 America/Los_Angeles",
                "original_purchase_date": "2022-11-24 18:05:01 Etc/GMT",
                "original_purchase_date_ms": "1669313101000",
                "original_purchase_date_pst": "2022-11-24 10:05:01 America/Los_Angeles",
                "is_trial_period": "false",
                "in_app_ownership_type": "PURCHASED"
            },
            {
                "quantity": "1",
                "product_id": "undo_3",
                "transaction_id": "240001281101159",
                "original_transaction_id": "240001281101159",
                "purchase_date": "2022-11-23 10:34:12 Etc/GMT",
                "purchase_date_ms": "1669199652000",
                "purchase_date_pst": "2022-11-23 02:34:12 America/Los_Angeles",
                "original_purchase_date": "2022-11-23 10:34:12 Etc/GMT",
                "original_purchase_date_ms": "1669199652000",
                "original_purchase_date_pst": "2022-11-23 02:34:12 America/Los_Angeles",
                "is_trial_period": "false",
                "in_app_ownership_type": "PURCHASED"
            }
        ]
    },
    "environment": "Production",
    "status": 0
}
```

Any advice would be appreciated, hopefully I'm just doing something wrong?
